name: Tests
on:
  workflow_call:
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true
jobs:
  test-project-id-issue-id:
    name: Specify id of project and id of issue
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add Project Item with Id
      id: add-issue-to-project
      uses: ./
      with:
        github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        project-id: 'PVT_kwHOAAzNIc4AFSrF'
        issue-id: 'I_kwDOGPYbTs5QpSG9'
    - name: Assert
      run: |
        [[ '${{ steps.add-issue-to-project.outputs.added-project-item-id }}' =~ '^PVTI_[a-zA-Z0-9]*$' ]]
    - name: TearDown
      uses: monry/delete-issue-from-project@develop
      with:
        github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        project-id: 'PVT_kwHOAAzNIc4AFSrF'
        project-item-id: ${{ inputs.added-project-item-id }}
