name: Tests
on:
  workflow_call:
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true
jobs:
  test-project-id-issue-id:
    name: Specify id of project and id of issue
    runs-on: ubuntu-latest
    outputs:
      added-project-item-id: ${{ steps.add-issue-to-project.outputs.added-project-item-id }}
    steps:
    - uses: actions/checkout@v2
    - name: Add Project Item with Id
      id: add-issue-to-project
      uses: ./
      with:
        github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        project-id: 'PVT_kwHOAAzNIc4AFSrF'
        issue-id: 'I_kwDOGPYbTs5QpSG9' # Fixture 01
    - name: Assert
      run: |
        [[ '${{ steps.add-issue-to-project.outputs.added-project-item-id }}' =~ '^PVTI_[a-zA-Z0-9]*$' ]]
  tear-down:
    name: TearDown tests
    uses: ./.github/workflows/tests-teardown.yml
    needs:
    - test-project-id-issue-id
    strategy:
      matrix:
        added-project-item-id:
        - ${{ needs.test-project-id-issue-id.outputs.added-project-item-id }}
    secrets: inherit
    with:
      added-project-item-id: ${{ matrix.added-project-item-id }}
