name: Tests TearDown
on:
  workflow_call:
    inputs:
      added-project-item-id:
        required: true
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true
jobs:
  remove-added-project-item:
    - uses: actions/checkout@v2
    - name: Remove Added Project Item
      uses: monry/remove-issue-from-project@develop
      with:
        github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        project-id: 'PVT_kwHOAAzNIc4AFSrF'
        project-item-id: ${{ inputs.added-project-item-id }}
